language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  # Speed up build time by disabling Xdebug.
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

  - travis_retry composer install --no-interaction --prefer-source  --classmap-authoritative

script:
  - vendor/bin/phpunit --no-coverage
